ROWS_FIELD = 25
COLS_FIELD = 50
CELL = 25
WINDOW_HEIGHT = CELL * ROWS_FIELD
WINDOW_WIDTH = CELL * COLS_FIELD


RED = (255, 89, 94)
GREEN = (138, 201, 38)
BLUE = (25, 130, 196)
ORANGE = (255, 202, 58)
VIOLET = (106, 76, 147)
BLACK = (0, 0, 0)
BACKGROUND_COLOR = (0, 125, 0)

BUSH_NUMBER = 20
MINE_NUMBER = 20
FLAG_PLACEMENT = [[21, 46], [21, 47], [21, 48], [21, 49],
                  [22, 46], [22, 47], [22, 48], [22, 49],
                  [23, 46], [23, 47], [23, 48], [23, 49]]

SOLDIER_START_PLACEMENT = [[4, 0], [4, 1]]  # first it is row and  second it is column

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

FONT_NAME = "Calibri"

SOLDER_SIZE_BY_WIDTH_IN_CELLS = 2
SOLDER_SIZE_BY_HEIGHT_IN_CELLS = 4

BUSH_SIZE_BY_WIDTH_IN_CELLS = 2
BUSH_SIZE_BY_HEIGHT_IN_CELLS = 3

MINE_SIZE_BY_WIDTH_IN_CELLS = 3
MINE_SIZE_BY_HEIGHT_IN_CELLS = 1

FLAG_SIZE_BY_WIDTH_IN_CELLS = 4
FLAG_SIZE_BY_HEIGHT_IN_CELLS = 3


SOLDER_SIZE = (CELL * SOLDER_SIZE_BY_WIDTH_IN_CELLS, CELL * SOLDER_SIZE_BY_HEIGHT_IN_CELLS)
BUSH_SIZE = (CELL * BUSH_SIZE_BY_WIDTH_IN_CELLS, CELL * BUSH_SIZE_BY_HEIGHT_IN_CELLS)
MINE_SIZE = (CELL * MINE_SIZE_BY_WIDTH_IN_CELLS, CELL * MINE_SIZE_BY_HEIGHT_IN_CELLS)
FLAG_SIZE = (CELL * FLAG_SIZE_BY_WIDTH_IN_CELLS, CELL * FLAG_SIZE_BY_HEIGHT_IN_CELLS)


EXPLOSION_IMAGE = r"source\explosion.png"
FLAG_IMAGE = r"source\flag.png"
BUSH_IMAGE = r"source\grass.png"
INJURY_IMAGE = r"source\injury.png"
MINE_IMAGE = r"source\mine.png"
SNAKE_IMAGE = r"source\snake.png"
SOLDIER_IMAGE = r"source\soldier.png"
DINO_IMAGE = r"source\dino.png"
SOLDER_NIGHT_IMAGE = r"source\soldier_night.png"
