ROWS_FIELD = 25
COLS_FIELD = 50
CELL = 25
WINDOW_HEIGHT = CELL * ROWS_FIELD
WINDOW_WIDTH = CELL * COLS_FIELD


RED = (255, 89, 94)
GREEN = (138, 201, 38)
BLUE = (25, 130, 196)
ORANGE = (255, 202, 58)
VIOLET = (106, 76, 147)
BLACK = (0, 0, 0)
WIGHT = (255, 255, 255)
BACKGROUND_COLOR = (0, 125, 0)

BUSH_NUMBER = 20
MINE_NUMBER = 20
FLAG_PLACEMENT = [[22, 46], [22, 47], [22, 48], [22, 49],
                  [23, 46], [23, 47], [23, 48], [23, 49],
                  [24, 46], [24, 47], [24, 48], [24, 49]]

SOLDIER_START_PLACEMENT = [[4, 0], [4, 1]]  # first it is row and  second it is column

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

FONT_NAME = "Calibri"

WELCOME_FIRST_MESSAGE = "Welcome to the flag game"
WELCOME_SECOND_MESSAGE = "Have fun!"
WELCOME_FONT_SIZE = int(0.02 * WINDOW_WIDTH)
WELCOME_COLOR = WIGHT
WELCOME_FIRST_LOCATION = CELL*3, CELL
WELCOME_SECOND_LOCATION = CELL*3, CELL*2

LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = 0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2)

WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = 0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2)

SOLDIER_SIZE_BY_WIDTH_IN_CELLS = 2
SOLDIER_SIZE_BY_HEIGHT_IN_CELLS = 4

BUSH_SIZE_BY_WIDTH_IN_CELLS = 2
BUSH_SIZE_BY_HEIGHT_IN_CELLS = 3

MINE_SIZE_BY_WIDTH_IN_CELLS = 3
MINE_SIZE_BY_HEIGHT_IN_CELLS = 1

EXPLOSION_SIZE_BY_WIDTH_IN_CELLS = 3
EXPLOSION_SIZE_BY_HEIGHT_IN_CELLS = 3

FLAG_SIZE_BY_WIDTH_IN_CELLS = 4
FLAG_SIZE_BY_HEIGHT_IN_CELLS = 3

TELEPORT_SIZE_BY_WIDTH_IN_CELLS = 3
TELEPORT_SIZE_BY_HEIGHT_IN_CELLS = 1

DINO_SIZE_BY_WIDTH_IN_CELLS = 2
DINO_SIZE_BY_HEIGHT_IN_CELLS = 4

SOLDIER_SIZE = (CELL * SOLDIER_SIZE_BY_WIDTH_IN_CELLS, CELL * SOLDIER_SIZE_BY_HEIGHT_IN_CELLS)
BUSH_SIZE = (CELL * BUSH_SIZE_BY_WIDTH_IN_CELLS, CELL * BUSH_SIZE_BY_HEIGHT_IN_CELLS)
MINE_SIZE = (CELL * MINE_SIZE_BY_WIDTH_IN_CELLS, CELL * MINE_SIZE_BY_HEIGHT_IN_CELLS)
EXPLOSION_SIZE = (CELL * EXPLOSION_SIZE_BY_WIDTH_IN_CELLS, CELL * EXPLOSION_SIZE_BY_HEIGHT_IN_CELLS)
FLAG_SIZE = (CELL * FLAG_SIZE_BY_WIDTH_IN_CELLS, CELL * FLAG_SIZE_BY_HEIGHT_IN_CELLS)
TELEPORT_SIZE = (CELL * TELEPORT_SIZE_BY_WIDTH_IN_CELLS, CELL * TELEPORT_SIZE_BY_HEIGHT_IN_CELLS)
DINO_SIZE = (CELL * DINO_SIZE_BY_WIDTH_IN_CELLS, CELL * DINO_SIZE_BY_HEIGHT_IN_CELLS)


EXPLOSION_IMAGE = r"source\explosion.png"
FLAG_IMAGE = r"source\flag.png"
BUSH_IMAGE = r"source\grass.png"
DAMAGED_SOLDIER_IMAGE = r"source\injury.png"
MINE_IMAGE = r"source\mine.png"
SNAKE_IMAGE = r"source\snake.png"
SOLDIER_IMAGE = r"source\soldier.png"
DINO_IMAGE = r"source\dino.png"
TELEPORT_IMAGE = r"source\teleport.png"
SOLDIER_NIGHT_IMAGE = r"source\soldier_night.png"

